# Generated by Django 2.2.16 on 2023-03-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230331_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, choices=[('#A9A9A9', 'DarkGray'), ('#FA8072', 'Salmon'), ('#FFB6C1', 'LightPink'), ('#FFA500', 'Orange'), ('#FFD700', 'Gold'), ('#D8BFD8', 'Thistle'), ('#98FB98', 'PaleGreen'), ('#AFEEEE', 'PaleTurquoise'), ('#66CDAA', 'MediumAquamarine')], default='#A9A9A9', max_length=7, null=True, verbose_name='Цвет'),
        ),
    ]
