# Generated by Django 2.2.16 on 2023-04-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230401_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('user',), 'verbose_name': 'Список покупок по рецепту', 'verbose_name_plural': 'Список покупок по рецептам'},
        ),
    ]
